Introduce Github actions for AWS ECS CI/CD
nestauk/asf_hp_market_tracker pull request #368
Opened 2023-09-20 15:57 UTC by doogyb

closes #330

2023-09-25 15:48 UTC, mindrones requested changes
Pass 1

2023-09-25 15:48 UTC, mindrones commented on .github/workflows/dev.yml
> +    branches: [ dev, 330_aws_ecs_ci_cd ]
I guess we need to remove `330_aws_ecs_ci_cd` :)

2023-09-25 15:48 UTC, mindrones commented on .github/workflows/dev.yml
> +
I think we need to re-enable this line?

2023-09-25 15:48 UTC, mindrones commented on be/.aws/hpmt_be_dev_task.json
> +{
If supported I'd use tabs in the jsons in `be/.aws`

2023-09-25 15:48 UTC, mindrones commented on be/package.json
> +		"@svizzle/utils": "^0.19.0",
I think this is a rebase error in that we upgraded Svizzle's versions in a previous commit

2023-09-25 15:48 UTC, mindrones commented on be/src/conf.js
> +export const index = 'hpmt_gold_interim_v7'
I'd reinstate the final `;` :)

2023-09-25 15:48 UTC, mindrones commented on be/src/routes.js
> +	fastify.get('/test', (_, reply) => reply.send('Shared workspace fix'));
Do we need this line?

2023-09-25 15:48 UTC, mindrones commented on be/src/hooks.js
> +			return;
Do we need this?

2023-09-26 13:26 UTC, mindrones approved these changes
Awesome, GTM!

2023-09-26 13:34 UTC, saabi commented on .github/workflows/production.yml
> +name: Deploy to Amazon ECS Dev service
Shouldn't this say `Production service`?

2023-09-26 13:34 UTC, saabi commented on .github/workflows/staging.yml
> +name: Deploy to Amazon ECS Dev service
Same as above: `Staging service`

2023-09-26 13:36 UTC, saabi approved these changes
Once the review comments are resolved, GTM

2023-09-26 13:46 UTC, merged