/fe: added initial statechart
nestauk/asf_hp_market_tracker pull request #40
Opened 2023-05-09 10:43 UTC by mindrones

closes #39

2023-05-15 12:09 UTC, saabi requested changes

2023-05-15 12:09 UTC, saabi commented on fe/src/lib/statechart/actions/view.js
> +	console.log('>>>>', event.data.data.agg1)
;

2023-05-17 13:32 UTC, doogyb approved these changes

2023-05-17 14:25 UTC, saabi approved these changes
GTM! Great work!

2023-05-17 16:07 UTC, merged